---
version: "3.7"
services:
  node_1:
    container_name: node_1
    image: cockroachdb/cockroach:latest
    volumes:
      - /tmp/data/node_1:/cockroach/cockroach-data
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      cockroach_net:
        aliases:
          - node_1

  node_2:
    container_name: node_2
    image: cockroachdb/cockroach:latest
    volumes:
      - /tmp/data/node_2:/cockroach/cockroach-data
    command: start --insecure --join=node_3
    networks:
      cockroach_net:
        aliases:
          - node_2

  node_3:
    container_name: node_3
    image: cockroachdb/cockroach:latest
    volumes:
      - /tmp/data/node_3:/cockroach/cockroach-data
    command: start --insecure --join=node_1
    networks:
      cockroach_net:
        aliases:
          - node_3

networks:
  cockroach_net:
    driver: bridge
